# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tektona < Formula
  desc "Tektona CLI — agentic development platform"
  homepage "https://tektona.ai"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v0.1.0/tektona_0.1.0_macOS_x86_64.tar.gz"
      sha256 "8053149416bfe4e7c1fe393ccca923540d0f2c9ab4e2018ca763251d8cda706a"

      define_method(:install) do
        bin.install "tektona"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v0.1.0/tektona_0.1.0_macOS_arm64.tar.gz"
      sha256 "6fbb01a6153edb4106b6b5abceebc6e7548b0009746bd9025d7e6203b2e1e5f5"

      define_method(:install) do
        bin.install "tektona"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v0.1.0/tektona_0.1.0_linux_x86_64.tar.gz"
      sha256 "c922e7f9d22ad2177b305cea14fa2d82740220e1e65db0fd28b2057097a9a068"
      define_method(:install) do
        bin.install "tektona"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v0.1.0/tektona_0.1.0_linux_arm64.tar.gz"
      sha256 "debdc9882a0ee0a10dd2e8318bcc6c210e7facf14627850c6e2744a2916f1222"
      define_method(:install) do
        bin.install "tektona"
      end
    end
  end

  test do
    system "#{bin}/tektona", "--help"
  end
end
