# This file was generated by GoReleaser. DO NOT EDIT.
cask "tektona" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "863fe1f4ada65be9b6dec77ef15988943b794139cad5c16898635802acc874a4"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9aa6cb8454109cb24c7d306058e4ddc06e1e411286279b3081f27a4ee9676162"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "81990f730a8550f702bc78c4e2ac0fa2a5bf1b5e7114159d00467a7bece29fe8"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6d07f23528876aaebd27ef42de3e86c8fc33ba7567a2a1b98f0d8d0834ed07fa"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tektona"
  desc "Tektona CLI — agentic development platform"
  homepage "https://tektona.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tektona"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tektona"]
  end

  # No zap stanza required

end
