# This file was generated by GoReleaser. DO NOT EDIT.
cask "tektona" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "94efc0b26ee79366b2a04bfb81a7b86921ff4b7d6ec9ef2d2b63524a15cd49ea"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0a93bb0574485114ed78492ffea0ec5a67408831cd0ac437bee8d015c2e1e5b1"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7acf14fcd56c3ad87783a1f6de15e95dae8ba361c082224074d2f74be24afcac"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8993c49f00ef550ad969662f16c42b340168f2491eae3bfed80d21fa65ac6ed1"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tektona"
  desc "Tektona CLI — agentic development platform"
  homepage "https://tektona.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tektona"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tektona"]
  end

  # No zap stanza required

end
