# This file was generated by GoReleaser. DO NOT EDIT.
cask "tektona" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "96e482d6563bb8b5a7d050e22bfacd893932a263ec70596526316dfeab6a2cd7"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a0a2376eadc0d514a91a476c03438ecaab89ae952dea771e86ee989c49172846"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c4ac121b0ad5c0f8b1e8a5b10038ae9b39610c8d4cb6c77d7baea0c6d153c1dd"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0ee93d696534c23c2c284b6e2793b62b07391c18743662f8563c56616390528e"
      url "https://github.com/tektona-ai/tektona-cli/releases/download/v#{version}/tektona_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tektona"
  desc "Tektona CLI — agentic development platform"
  homepage "https://tektona.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tektona"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tektona"]
  end

  # No zap stanza required

end
